[versions]
agp = "8.10.0"
constraintlayout = "2.2.1"
min-sdk = "23"
target-sdk = "35"
compile-sdk = "35"
material = "1.12.0"
kotlin = "2.1.21"
appcompat = "1.7.0"
androidx-junit = "1.2.1"
androidx-monitor = "1.7.2"
core-ktx = "1.16.0"
detekt = "1.23.6"
espresso-core = "3.6.1"
junit = "4.13.2"
publish = "2.0.0"
ui-test-junit4-android = "1.8.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-test-monitor = { module = "androidx.test:monitor", version.ref = "androidx-monitor" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
espresso-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.6.2" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "ui-test-junit4-android" }
differ = "com.dropbox.differ:differ:0.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish" }