[versions]
agp = "8.4.1"
common = "31.4.1"
ddmlib = "31.4.1"
kotlin = "1.9.23"
detekt = "1.23.6"
publish-plugin = "1.2.0"

[libraries]
android-builder-test-api = { module = "com.android.tools.build:builder-test-api", version.ref = "agp" }
android-common = { module = "com.android.tools:common", version.ref = "common" }
android-ddmlib = { module = "com.android.tools.ddms:ddmlib", version.ref = "ddmlib" }
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish-plugin = { id = "com.gradle.plugin-publish", version.ref = "publish-plugin" }
